trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6'
    addToPath: true

- script: bundle exec rake
  displayName: 'bundle exec rake'
